version: "3.1"

services:
  app:
      container_name: flask_api
      build: .
      ports:
        - '5000:5000'
      volumes:
        - .:/short-url

  db:
    container_name: postgres_db
    image: postgres:latest
    restart: always
    user: 1000:1000
    environment:
      POSTGRES_DB: shorturl
      POSTGRES_USER: shorturl
      POSTGRES_PASSWORD: your_password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql:/var/lib/postgresql/data

  redis:
    container_name: redis_db
    image: redis
    command: redis-server --requirepass your_password
    ports:
      - "6379:6379"
