name: CI

on:
  push:
    branches: [ develop ]
    
  workflow_dispatch:

env:
  WORKING_DIRECTORY: 'api_flask'
  PYTHON_VERSION: '3.10.10'

jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: python install
        run: |
         sudo apt install libpq-dev gcc -y
         sudo apt install python3-venv
         python -m venv --copies venv
         source venv/bin/activate
         pip install setuptools
         pip install -r requirements.txt
      
      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "."
          target: "api_flask"
          
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd api_flask
            ln -sf /var/lib/postgresql
            docker compose stop
            docker compose build
            docker compose up -d
