name: CI

on:
  push:
    branches: [ develop ]
    
  workflow_dispatch:

env:
  WORKING_DIRECTORY: 'api_flask'
  PYTHON_VERSION: '3.10.10'

jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: python install
        run: |
         sudo apt install libpq-dev gcc -y
         sudo apt install python3-venv
         python -m venv --copies antenv
         source antenv/bin/activate
         pip install setuptools
         pip install -r requirements.txt
